name: NewPerm
version: 2.0.5
main: me.newdavis.plugin.NewPerm
description: Manage the Player Permissions or Roles with this Permission Plugin.
author: NewDavis
website: https://newdavis.me/

commands:
  newperm:
    aliases: [np]